import type { Bookmark } from "./types";

/**
 * Predefined bookmarks shipped on first load. The user's own entries are merged
 * on top; presets are identified by `preset: true` so we never re-seed them
 * twice and the UI can flag them visually.
 */
export const PRESET_BOOKMARKS: Bookmark[] = [
  {
    id: "preset-jaunt",
    title: "Jaunt",
    url: "https://jaunt.pages.dev",
    description: "A small expedition into spatial UI.",
    category: "personal",
    tags: ["sketch", "spatial"],
    favorite: true,
    classification: "PS · 005.74",
    createdAt: Date.parse("2025-09-12"),
    preset: true,
  },
  {
    id: "preset-jref",
    title: "j-ref",
    url: "https://j-ref.pages.dev",
    description: "A personal reference index — notes, links, fragments.",
    category: "personal",
    tags: ["notes", "index"],
    favorite: true,
    classification: "PS · 020.12",
    createdAt: Date.parse("2025-10-03"),
    preset: true,
  },
  {
    id: "preset-portfolio",
    title: "Studio Notes",
    url: "https://jay.work",
    description: "Selected projects and writing.",
    category: "personal",
    tags: ["portfolio", "writing"],
    favorite: false,
    classification: "PS · 700.04",
    createdAt: Date.parse("2025-06-22"),
    preset: true,
  },
  {
    id: "preset-anthropic",
    title: "Anthropic",
    url: "https://www.anthropic.com",
    description: "Research lab building reliable, interpretable systems.",
    category: "work",
    tags: ["ai", "research"],
    favorite: false,
    classification: "WK · 006.30",
    createdAt: Date.parse("2025-04-01"),
    preset: true,
  },
  {
    id: "preset-shadcn",
    title: "shadcn / ui",
    url: "https://ui.shadcn.com",
    description: "Open-code component primitives — copy what you need.",
    category: "tools",
    tags: ["ui", "components", "react"],
    favorite: false,
    classification: "TL · 005.13",
    createdAt: Date.parse("2025-02-18"),
    preset: true,
  },
  {
    id: "preset-astro",
    title: "Astro",
    url: "https://astro.build",
    description: "The web framework for content-driven websites.",
    category: "tools",
    tags: ["framework", "ssg"],
    favorite: false,
    classification: "TL · 005.27",
    createdAt: Date.parse("2025-01-09"),
    preset: true,
  },
  {
    id: "preset-radix",
    title: "Radix Primitives",
    url: "https://www.radix-ui.com",
    description: "Unstyled, accessible component primitives.",
    category: "tools",
    tags: ["accessibility", "react"],
    favorite: false,
    classification: "TL · 005.42",
    createdAt: Date.parse("2025-03-11"),
    preset: true,
  },
  {
    id: "preset-pudding",
    title: "The Pudding",
    url: "https://pudding.cool",
    description: "Visual essays explaining ideas with data.",
    category: "reading",
    tags: ["data", "essay"],
    favorite: false,
    classification: "RD · 070.10",
    createdAt: Date.parse("2025-05-19"),
    preset: true,
  },
  {
    id: "preset-cabel",
    title: "Cabel.com",
    url: "https://cabel.com",
    description: "Cabel Sasser's playful corner of the web.",
    category: "reading",
    tags: ["weblog", "indie"],
    favorite: false,
    classification: "RD · 814.54",
    createdAt: Date.parse("2025-08-02"),
    preset: true,
  },
  {
    id: "preset-arena",
    title: "Are.na",
    url: "https://are.na",
    description: "Collaborative research and visual collection.",
    category: "reading",
    tags: ["research", "moodboard"],
    favorite: false,
    classification: "RD · 025.06",
    createdAt: Date.parse("2025-07-14"),
    preset: true,
  },
  {
    id: "preset-neal",
    title: "Neal.fun",
    url: "https://neal.fun",
    description: "Interactive curios from Neal Agarwal.",
    category: "play",
    tags: ["games", "interactive"],
    favorite: false,
    classification: "PL · 793.93",
    createdAt: Date.parse("2025-03-28"),
    preset: true,
  },
  {
    id: "preset-bruno",
    title: "Bruno Simon",
    url: "https://bruno-simon.com",
    description: "A portfolio you drive around in a 3D car.",
    category: "play",
    tags: ["3d", "webgl"],
    favorite: false,
    classification: "PL · 006.69",
    createdAt: Date.parse("2025-02-02"),
    preset: true,
  },
];
